public class Address {
    public void homeAddress(){
string myName = 'Naciye';
System.debug('my name is; ' + myName);
integer TotalFamilyMember = 4;
System.debug('My number of total member: ' + TotalFamilyMember);
string HouseName = 'Single House';
System.debug('My house is '+ HouseName);
integer HouseNumber = 23020;
System.debug(HouseNumber);
string StreetName = 'PheasentRun';
System.debug(StreetName);
string CityName = 'St.Louis';
System.debug(CityName);
string StateName = 'Missouri';
System.debug(StateName);
string StateISOCode = 'US-MO';
System.debug(StateISOCode);
string CountryName = 'USA';
System.debug(CountryName);
integer CountryISOCode = 340;
System.debug(CountryISOCode);
integer ZipCode = 63043;
System.debug(ZipCode);
Boolean IsCurrentHome= false;
System.debug(IsCurrentHome);

    }
}
